name: sample workflow
on:
  push:
    branches:
      - main
jobs:
  sample-build:
    runs-on: ubuntu-latest
    steps:
      - name: my-actions
        uses: .
      - name: Successful
        run: echo "My actions works"
